---
title: '0415'
author: '410873113'
date: "2020/4/15"
output: html_document
---

在前面討論使用$及[]取一個元素時我們創造了get1與get2兩個物件，請分別由get1, get2取出108-1學期個體經濟學教師姓名。

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
```

```{r}
str(listExample)
```

```{r}
get1<-listExample[["學期"]] #拿出來
get1<-listExample$`學期`

get2<-listExample["學期"]#只留下
```

###get1取出

```{r}
get1$`108-1`-> get1_layer1
str(get1_layer1)
```

```{r}
get1_layer1[[1]]-> get1_layer2;get1_layer2
str(get1_layer2)
```

```{r}
get1_layer2$teacher
```

```{r}
get1<-listExample[["學期"]]
get1$`108-1`-> get1_layer1
get1_layer1[[1]]-> get1_layer2
get1_layer2$teacher

listExample[["學期"]]$`108-1`[[1]]$teacher
```



###get2取出

```{r}
get2 <- listExample["學期"]#只留下
get2_layer1 <- get2[[1]]
get2_layer2 <-get2_layer1[["108-1"]]
get2_layer3 <- get2_layer2[[1]]
get2_layer3$teacher
```

```{r}
listExample["學期"][[1]][["108-1"]][[1]]$teacher
```

##list應用

```{r}
today <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))
tomorrow <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))

weather <- list(today,tomorrow)

print(weather)
```

```{r}
today <- list(
  list("台北市",
       highest_temp=c(highest_temp = 25),
       lowest_temp=c(lowest_temp = 18)),
  list("新北市",
       highest_temp=c(highest_temp = 24),
       lowest_temp=c(lowest_temp = 15)))
```

```{r}
today[[1]]$highest_temp
```

4-2 新增/替換/刪除元素

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
a
```
```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

