---
title: "Untitled"
author: '410873113'
date: "2020/5/13"
output: html_document
---

#####4.7 On factor class
內定levels順序是根據電腦內字元排序（collating sequence）依辭典序列方式決定排序，很多時候沒有意義。

```{r}
char1 <- c("Wild","Apple","Donald","May","Avocada") 
factor1 <- factor(char1)
levels(factor1)
```

```{r}
library(stringr)
char2 <- c("蔡英文","習近平","Donald Trump","蔡頭") 
factor2 <- factor(char2)
levels(factor2)

sort(
  str_sub(char2,1,1)
)
sort(
  str_sub(char2,2,2)
)
```

##查詢你的collating sequence設定：
```{r}
Sys.getlocale("LC_COLLATE")
```

##嚴重特殊傳染性肺炎


```{r}
jsonlite::fromJSON("https://od.cdc.gov.tw/eic/Day_Confirmation_Age_County_Gender_19CoV.json") -> covid19
```
```{r}
# 不可排序類別：性別、縣市、是否境外移入
covid19$`縣市` <- 
  factor(covid19$`縣市`)
covid19$`性別` <-
  factor(covid19$`性別`)
covid19$`是否為境外移入` <-
  factor(
    covid19$`是否為境外移入`
  )
```

```{r}
# 可排序類別資料：年齡層
covid19$`年齡層` <-
  factor(
    covid19$`年齡層`,
    ordered=TRUE
  )
```

```{r}
levels(covid19$`縣市`)
levels(covid19$`性別`)
levels(covid19$`是否為境外移入`)
```
```{r}
covid19$`年齡層`
levels(covid19$`年齡層`)
```






































































































































































































































