---
title: "Untitled"
author: '410873113'
date: "2020/5/20"
output: html_document
---

####4.8 On list

```{r}
library(purrr)
```

##4.8.1 每個元素相同運算

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

#我們有可能想要拿出其中屬於小新的資料：

```{r}
pick_小新 <- example$name == "小新"
data_selected <- 
  list(
    name=example$name[pick_小新],
    weight=example$weight[pick_小新],
    height=example$height[pick_小新],
    hobby=example$hobby[pick_小新],
    residence=example$residence[pick_小新],
    allowance=example$allowance[pick_小新],
    bloodType=example$bloodType[pick_小新]
  )
#data_selected的產生，相當於進行

example[[1]][pick_小新]
example[[2]][pick_小新]
example[[3]][pick_小新]
example[[4]][pick_小新]
example[[5]][pick_小新]
example[[6]][pick_小新]
example[[7]][pick_小新]
```

##再存放在list()裡。也就是我們想要：

對example底下的每個元素進行

[pick_小新]的動作

purrr底下的map()允許我們

使用.x來代表每個元素，即[[1]], [[2]], ..., [[7]]
所以

對每個元素進行[pick_小新]

可以寫成.x[pick_小新]。

對 example 底下的每個元素進行

.x[pick_小新] 的動作

```{r}
map(example, ~.x[pick_小新]) -> 
  data_selected 
  
data_selected
```

##舞蹈表演

```{r}
jsonlite::fromJSON("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=3", simplifyDataFrame = F) -> dance
```
```{r}
str(dance)
```

```{r}
# 第一個dance表演名稱
dance[[1]]$title
# 第二個dance表演名稱
dance[[2]]$title
```
##利用map

```{r}
map(dance,~.x$title)->
  list_titles

View(list_titles)
```

##每個表演有時不止演出一場，每個表演的場次總數：

```{r}
# 記載第一個表演的所有場次訊息
dance[[1]]$showInfo
str(dance[[1]]$showInfo)
# 計算第一個表演有幾個場次
length(dance[[1]]$showInfo)
# 計算第二個表演有幾個場次
length(dance[[2]]$showInfo)
```

對 dance 每個元素進行

length(.x$showInfo)的動作

```{r}
map(dance,~length(.x$showInfo)) ->
  list_numberOfShows 
  
View(list_numberOfShows)
```





























































































































































































